### PR TITLE
SMP: Make it compile on gcc-9 for debian

### PR DESCRIPTION
**Pull request by zamaudio**
This applies all the current patches from debian's gnumach, plus a couple of changes of my own for fixing the docs and gcc9 support.  You can find the original debian patches here: https://salsa.debian.org/hurd-team/gnumach/tree/master/debian/patches

### CODE REVIEW

**Comment by zamaudio** [comment]
I suggest keeping this patch separate otherwise it will be difficult to merge upstream to gnumach if you use debian specific patches...

**Review by AlmuHS — COMMENTED** [review]
You missed to add `kern/experimental.server.h`  file

**Comment by zamaudio** [comment]
@AlmuHS I'm pretty sure that file is autogenerated from other files that are already included.

**Comment by AlmuHS** [comment]
The building process failed, telling that this  file don't exist. Tomorrow I can repeat It. 

El Lunes 28 de octubre de 2019, Damien Zammit escribió:
> @AlmuHS I'm pretty sure that file is autogenerated from other files that are already included.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/AlmuHS/GNUMach_SMP/pull/10#issuecomment-54675283

-- 
Enviado desde mi dispositivo Sailfish

**Comment by zamaudio** [comment]
I'll take a look this evening, if it's missing I will force push to this branch with a fix.

**Comment by AlmuHS** [comment]
> I'll take a look this evening, if it's missing I will force push to this branch with a fix.

Finally, I got solved after compile inside Debian GNU/Hurd

**Pull request closed without merging**
